ots/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('activate-user/<uidb64>/<token>',
         views.activate_user, name='activate'),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html"), name="reset_password"),
    #path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_sent.html"), name="password_reset_done"),
    #path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    #path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path('', views.login_view, name="Home"),
]

ots/main/urls.py
from django.urls import path

from . import views

app_name = 'articles'


urlpatterns = [
    path('', views.homepage, name="list"),
    path('contact/$', views.contact, name="contact"),
    path('hotelReview/$', views.hotelReview, name="hotelReview"),
    path('deleteHotelReview/<str:pk>/$', views.deleteHotelReview, name="deleteHotelReview"),
    path('resturantReview/$', views.resturantReview, name="resturantReview"),
    path('deleteResturantReview/<str:pk>/$', views.deleteresturantReview, name="deleteResturantReview"),
    path('placeReview/$', views.placeReview, name="placeReview"),
    path('deleteplaceReview/<str:pk>/$', views.deleteplaceReview, name="deleteplaceReview"),

    path('reservation_new/$', views.reservationnew, name="reservation_new"),
    path('hotel_bookingPdf', views.hotel_bookingPdf, name="hotel_bookingPdf"),

    path('hotel_page/$', views.hotel_page, name="hotel_page"),
    path('room/$', views.RoomShow, name="RoomShow"),

    path('placelist/$', views.placelist, name="placelist"),
    path('place/$', views.place, name="place"),

    path('resturant/$', views.resturantShow, name="resturantShow"),
    path('resturantList/$', views.resturantList, name="resturantList"),

    path('cultural_food/$', views.culturalfood, name="cultural_food"),
    path('contact_new/$', views.contactNew, name="contact_new"),
    path('about/$', views.about, name="about"),
    path('faqs/$', views.faqs, name="faqs"),



    path('user_profile/$', views.UserProfile, name="user_profile"),
    path('create_profile/$', views.createProfile, name="create_profile"),

    path('direct_message/$', views.directmessage, name="direct_message"),
    path('sent_message/$', views.sentmessage, name="sent_message"),

    path('chat_forum/$', views.chatForum, name="chat_forum"),

    path('wishlist/$', views.wishList, name="wishlist"),
    path('deletewishlist/<str:pk>/$', views.deletewishlist, name="deletewishlist"),


    path('hotelsearch/$', views.hotelsearch, name="hotelsearch"),
    path('placesearch/$', views.placesearch, name="placesearch"),
    path('resturantsearch/$', views.resturantsearch, name="resturantsearch"),

    path('blogList/$', views.blogList, name="blogList"),
    path('blogPage/<str:pk>/$', views.blogPage, name="blogPage"),
    path('deleteBlog/<str:pk>/$', views.deleteBlog, name="deleteBlog"),
    path('createBlog/$', views.createBlog, name="createBlog"),
    path('editBlogs/<str:pk>/$', views.editBlogs, name="editBlogs"),

    path('usersearch/$', views.usersearch, name="usersearch"),
    path('searcheduser/$', views.searcheduser, name="searcheduser"),
    path('searchedUserProfile/<str:pk>/$', views.searchedUserProfile, name="searchedUserProfile"),

    path('appRating/$', views.appRating, name="appRating"),
    path('showAppRating/$', views.showAppRating, name="showAppRating"),
    path('deleteAppRating/<str:pk>/$', views.deleteAppRating, name="deleteAppRating"),

]

ots/ots/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('social_django.urls', namespace='social')),
    path('accounts/', include('accounts.urls')),
    path('main/', include('main.urls')),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_form.html"), name="password_reset_confirm"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_sent.html"), name="password_reset_done"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_complete.html"), name="password_reset_complete"),
    path('', views.homepage),
    path('media/(?P<path>.*)$', serve, {'document_root':       settings.MEDIA_ROOT}),
    path('static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),


]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ots/templates/base_layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/static/style.css">
    <link rel="stylesheet" href="/static/ticket.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://code.jquery.com/jquery-3.5.0.js"></script>
    <style>
body {
  font-family: Arial, Helvetica, sans-serif;
  margin: 0;
}

html {
  box-sizing: border-box;
}

*, *:before, *:after {
  box-sizing: inherit;
}

.column {
  float: left;
  width: 33.3%;
  margin-bottom: 16px;
  padding: 0 8px;
}

.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  margin: 8px;
}

.about-section {
  padding: 50px;
  text-align: center;
  background-color: #474e5d;
  color: white;
}
.txt-white{
    color: white;
}

.container {
  padding: 0 16px;
}

.container::after, .row::after {
  content: "";
  clear: both;
  display: table;
}

.title {
  color: grey;
}

.button {
  border: none;
  outline: 0;
  display: inline-block;
  padding: 8px;
  color: white;
  background-color: #000;
  text-align: center;
  cursor: pointer;
  width: 100%;
}

.button:hover {
  background-color: #555;
}

@media screen and (max-width: 650px) {
  .column {
    width: 100%;
    display: block;
  }
}
.dropbtn {
  background-color: rgba(100, 100, 100, 0.5);
  color: white;
  padding: 16px;
  font-size: 16px;
  border: none;
  cursor: pointer;
}

.dropdown {
  position: relative;
  display: inline-block;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f9f9f9;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
}

.dropdown-content a:hover {background-color: rgba(100, 100, 100, 0.5);}

.dropdown:hover .dropdown-content {
  display: block;
}

.dropdown:hover .dropbtn {
  background-color: rgba(100, 100, 100, 0.5);
}
.left-padding{
padding-right: 50px;
}

.roundbutton1{
border-radius: 50%;
}
</style>
<title>Green Travel</title>         
        <link href="/static/home/css/style.css" rel="stylesheet">
        <link rel="shortcut icon" href="/static/home/img/favicon.ico">
         
        
        <!------------Responsive css file------------->         
        <link href="/static/home/css/responsive.css" rel="stylesheet" type="text/css">  
                 
        <!-------------Magnific popup css file------------->
        <link href="/static/home/css/magnific-popup.css" rel="stylesheet" type="text/css"> 
        
        <!-------------Magnific popup css file------------->        
         <link href="/static/home/css/owl.carousel.min.css" rel="stylesheet" type="text/css"> 
         <link href="/static/home/css/owl.theme.default.min.css" rel="stylesheet" type="text/css">              
                                                   
        <!-------------Font Awesome cdn files------------->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">  
               
        <!-------------Font Awesome cdn ends------------->
         
        <!-- Latest compiled and minified CSS -->
       <link rel="stylesheet" href="/static/home/css/bootstrap.min.css" type="text/css"> 
                  
        <!-------------Animate css file------------->
        <link href="/static/home/css/animate.css" type="text/css" rel="stylesheet">
        
       <!-- jQuery library -->
       <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
                        
        <!-------------Owl Carousel Js file------------->
        <script src="/static/home/js/owl.carousel.min.js" type="text/javascript"></script>  
                      
        <!-------------Magnific popup Js file------------->
       <script src="/static/home/js/jquery.magnific-popup.min.js" type="text/javascript"></script>
        
       <!-- Latest compiled JavaScript -->
       <script src="/static/home/js/bootstrap.min.js" type="text/javascript"></script>
       <!-- Start of Async Drift Code -->
       <script>
       !function() {
         var t;
         if (t = window.driftt = window.drift = window.driftt || [], !t.init) return t.invoked ? void (window.console && console.error && console.error("Drift snippet included twice.")) : (t.invoked = !0, 
         t.methods = [ "identify", "config", "track", "reset", "debug", "show", "ping", "page", "hide", "off", "on" ], 
         t.factory = function(e) {
           return function() {
             var n;
             return n = Array.prototype.slice.call(arguments), n.unshift(e), t.push(n), t;
           };
         }, t.methods.forEach(function(e) {
           t[e] = t.factory(e);
         }), t.load = function(t) {
           var e, n, o, i;
           e = 3e5, i = Math.ceil(new Date() / e) * e, o = document.createElement("script"), 
           o.type = "text/javascript", o.async = !0, o.crossorigin = "anonymous", o.src = "/static/home/https://js.driftt.com/include/" + i + "/" + t + ".js", 
           n = document.getElementsByTagName("script")[0], n.parentNode.insertBefore(o, n);
         });
       }();
       drift.SNIPPET_VERSION = '0.3.1';
       drift.load('u4k3vh36tbfn');
       </script>
       <!-- End of Async Drift Code -->
</head>
<body>
<!-- <div class="topnav">
        <a class="active" href="/main">Home</a>

        <a href="{% url 'articles:about' %}">About</a>
        <a href="{% url 'articles:contact' %}">Contact Us</a>


    </div> -->
    <!-- <div class="dropdown-- " >
      <button class="dropbtn roundbutton1" >{{ user.username }}</button>
      <div class="dropdown-content">
      <a><form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                    {% csrf_token %}
          <button type="submit" class="dropbtn ">Logout</button>
      </form></a>
      </div>
    </div> -->

    <div class="Wrapper">

        {% block content %}
        {% endblock %}
    </div>
</body>
</html>