ots/main/urls.py
from django.urls import path

from . import views

app_name = 'articles'


urlpatterns = [
    path('', views.homepage, name="list"),
    path('contact/$', views.contact, name="contact"),
    path('hotelReview/$', views.hotelReview, name="hotelReview"),
    path('deleteHotelReview/<str:pk>/$', views.deleteHotelReview, name="deleteHotelReview"),
    path('resturantReview/$', views.resturantReview, name="resturantReview"),
    path('deleteResturantReview/<str:pk>/$', views.deleteresturantReview, name="deleteResturantReview"),
    path('placeReview/$', views.placeReview, name="placeReview"),
    path('deleteplaceReview/<str:pk>/$', views.deleteplaceReview, name="deleteplaceReview"),

    path('reservation_new/$', views.reservationnew, name="reservation_new"),
    path('hotel_bookingPdf', views.hotel_bookingPdf, name="hotel_bookingPdf"),

    path('hotel_page/$', views.hotel_page, name="hotel_page"),
    path('room/$', views.RoomShow, name="RoomShow"),

    path('placelist/$', views.placelist, name="placelist"),
    path('place/$', views.place, name="place"),

    path('resturant/$', views.resturantShow, name="resturantShow"),
    path('resturantList/$', views.resturantList, name="resturantList"),

    path('cultural_food/$', views.culturalfood, name="cultural_food"),
    path('contact_new/$', views.contactNew, name="contact_new"),
    path('about/$', views.about, name="about"),
    path('faqs/$', views.faqs, name="faqs"),



    path('user_profile/$', views.UserProfile, name="user_profile"),
    path('create_profile/$', views.createProfile, name="create_profile"),

    path('direct_message/$', views.directmessage, name="direct_message"),
    path('sent_message/$', views.sentmessage, name="sent_message"),

    path('chat_forum/$', views.chatForum, name="chat_forum"),

    path('wishlist/$', views.wishList, name="wishlist"),
    path('deletewishlist/<str:pk>/$', views.deletewishlist, name="deletewishlist"),


    path('hotelsearch/$', views.hotelsearch, name="hotelsearch"),
    path('placesearch/$', views.placesearch, name="placesearch"),
    path('resturantsearch/$', views.resturantsearch, name="resturantsearch"),

    path('blogList/$', views.blogList, name="blogList"),
    path('blogPage/<str:pk>/$', views.blogPage, name="blogPage"),
    path('deleteBlog/<str:pk>/$', views.deleteBlog, name="deleteBlog"),
    path('createBlog/$', views.createBlog, name="createBlog"),
    path('editBlogs/<str:pk>/$', views.editBlogs, name="editBlogs"),

    path('usersearch/$', views.usersearch, name="usersearch"),
    path('searcheduser/$', views.searcheduser, name="searcheduser"),
    path('searchedUserProfile/<str:pk>/$', views.searchedUserProfile, name="searchedUserProfile"),

    path('appRating/$', views.appRating, name="appRating"),
    path('showAppRating/$', views.showAppRating, name="showAppRating"),
    path('deleteAppRating/<str:pk>/$', views.deleteAppRating, name="deleteAppRating"),

]

ots/ots/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('social_django.urls', namespace='social')),
    path('accounts/', include('accounts.urls')),
    path('main/', include('main.urls')),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_form.html"), name="password_reset_confirm"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_sent.html"), name="password_reset_done"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_complete.html"), name="password_reset_complete"),
    path('', views.homepage),
    path('media/(?P<path>.*)$', serve, {'document_root':       settings.MEDIA_ROOT}),
    path('static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),


]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ots/main/models.py
from django.conf import settings
from django.db import models

RATE_CHOICES = [
    (1, '1 - Trash'),
    (2, '2- Horrible'),
    (3, '3- Terrible'),
    (4, '4- Bad'),
    (5, '5- OK'),
    (6, '6- Rideable'),
    (7, '7- Good'),
    (8, '8- Very good'),
    (9, '9- Perfect'),
    (10, '10- Best'),

]

HotelChoices = [
    ('Pan_Pacific_Sonargoan', 'Pan Pacific Sonargoan'),
    ('Radisson_Blu', 'Radisson Blu'),
    ('Hotel_De_Meridian', 'Hotel De Meridian'),
    ('Grand_Plaza_Hotel', 'Grand Plaza Hotel'),
    ('Empyrean_Hotel', 'Empyrean Hotel'),
    ('The_Raintree_Dhaka', 'The Raintree Dhaka')
]

ResturantChoices = [
    ('Istanbul_Restaurant', 'Istanbul Restaurant'),
    ('The_Dining_Lounge', 'The Dining Lounge'),
    ('Sultans_Dine', 'Sultans Dine'),
    ('Pizza_Hut', 'Pizza Hut'),
    ('Chillox', 'Chillox'),
    ('Khanas', 'Khanas'),
    ('Burger_King', 'Burger King'),
    ('Kacchi_Vai', 'Kacchi Vai')
]

PlaceChoices = [
    ('Dhaka', 'Dhaka'),
    ('Cox_Bazar', 'Cox-Bazar'),
    ('Sylhet', 'Sylhet'),
    ('Cumilla', 'Cumilla'),
    ('Gazipur', 'Gazipur'),
    ('Rajshahi', 'Rajshahi')
]


class HotelReview(models.Model):
    name = models.CharField(max_length=20)
    date = models.DateTimeField(auto_now_add=True)
    hotelName = models.CharField(choices=HotelChoices, max_length=100, default=None, null=True)
    review = models.TextField(max_length=3000, blank=True)
    rating = models.PositiveSmallIntegerField(choices=RATE_CHOICES, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=None, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.name


class ResturantReview(models.Model):
    name = models.CharField(max_length=20)
    date = models.DateTimeField(auto_now_add=True)
    resturantName = models.CharField(choices=ResturantChoices, max_length=100, default=None, null=True)
    review = models.TextField(max_length=3000, blank=True)
    rating = models.PositiveSmallIntegerField(choices=RATE_CHOICES, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=None, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.name


class PlaceReview(models.Model):
    name = models.CharField(max_length=20)
    date = models.DateTimeField(auto_now_add=True)
    placeName = models.CharField(choices=PlaceChoices, max_length=100, default=None, null=True)
    review = models.TextField(max_length=3000, blank=True)
    rating = models.PositiveSmallIntegerField(choices=RATE_CHOICES, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=None, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.name


class HotelReservation(models.Model):
    user_name = models.CharField(max_length=20)
    user_email = models.CharField(max_length=30)
    user_phone = models.CharField(max_length=20)
    checkin_date = models.CharField(max_length=20)
    checkout_date = models.CharField(max_length=20)
    hotel_name = models.CharField(max_length=20)
    room_number = models.CharField(max_length=20)
    room_type = models.CharField(max_length=20)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=None, on_delete=models.DO_NOTHING)


class RoomModel(models.Model):
    roomtype = models.CharField(max_length=20)
    beds = models.CharField(max_length=20)
    baths = models.CharField(max_length=20)
    slug = models.SlugField()
    guests = models.IntegerField()
    amenities = models.TextField(max_length=3000, blank=True)
    facilities = models.TextField(max_length=3000, blank=True)
    room_Img1 = models.ImageField(blank=True, null=True)
    room_Img2 = models.ImageField(blank=True, null=True)
    room_Img3 = models.ImageField(blank=True, null=True)


class Place(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField()
    description = models.TextField(max_length=3000, blank=True)
    route = models.TextField(max_length=3000, blank=True)
    map_link = models.TextField(max_length=3000, blank=True)
    place_Img1 = models.ImageField(blank=True, null=True)
    place_Img2 = models.ImageField(blank=True, null=True)
    place_Img3 = models.ImageField(blank=True, null=True)


class ResturantInfo(models.Model):
    name = models.CharField(max_length=300)
    slug = models.SlugField()
    address = models.TextField(max_length=3000, blank=True)
    description = models.TextField(max_length=3000, blank=True)
    menu = models.TextField(max_length=3000, blank=True)
    website = models.CharField(max_length=500)
    res_img = models.ImageField(blank=True, null=True)


class userProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, null=True, on_delete=models.CASCADE)
    user_name = models.CharField(max_length=300, null=True)
    user_phone = models.CharField(max_length=20, null=True)
    user_address = models.CharField(max_length=20, null=True)
    date = models.DateTimeField(auto_now_add=True)
    bio = models.CharField(max_length=300, null=True)
    user_image = models.ImageField(blank=True, null=True, upload_to='media', default='user.png')


class chat(models.Model):
    from_user = models.ForeignKey(settings.AUTH_USER_MODEL, default=None, on_delete=models.DO_NOTHING, related_name='from_user')
    to_user = models.ForeignKey(settings.AUTH_USER_MODEL, default=None, on_delete=models.DO_NOTHING, related_name='to_user')
    chat = models.CharField(max_length=300, null=True)
    date = models.DateTimeField(auto_now_add=True)


class chatForumMessages(models.Model):
    message_user = models.ForeignKey(settings.AUTH_USER_MODEL, default=None, on_delete=models.DO_NOTHING)
    message = models.CharField(max_length=300, null=True)
    date = models.DateTimeField(auto_now_add=True)


class wishlist(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=None, on_delete=models.DO_NOTHING)
    PlaceName = models.CharField(choices=PlaceChoices, max_length=100, default=None, null=True, unique=True)
    date = models.DateTimeField(auto_now_add=True)


class userBlog(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=None, on_delete=models.DO_NOTHING)
    Title = models.CharField(max_length=300, null=True, blank=True)
    text = models.TextField(max_length=3000, blank=True)
    place_Img1 = models.ImageField(blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True, null=True)


class appReview(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=None, on_delete=models.DO_NOTHING)
    comment = models.TextField(max_length=250)
    rate = models.IntegerField(default=0)
    date = models.DateTimeField(auto_now_add=True)

ots/main/forms.py
from django import forms
from . import models


class HotelReview(forms.ModelForm):
    class Meta:
        model = models.HotelReview
        fields = ['name', 'hotelName', 'review', 'rating']


class ResturantReview(forms.ModelForm):
    class Meta:
        model = models.ResturantReview
        fields = ['name', 'resturantName', 'review', 'rating']


class PlaceReview(forms.ModelForm):
    class Meta:
        model = models.PlaceReview
        fields = ['name', 'placeName', 'review', 'rating']


class UserProfile(forms.ModelForm):
    class Meta:
        model = models.userProfile
        fields = ['user_name', 'user_phone', 'user_address', 'bio', 'user_image']


class chatForm(forms.ModelForm):
    class Meta:
        model = models.chat
        fields = ['to_user', 'chat']


class chatForumForm(forms.ModelForm):
    class Meta:
        model = models.chatForumMessages
        fields = ['message']


class wishlistForm(forms.ModelForm):
    class Meta:
        model = models.wishlist
        fields = ['PlaceName']


class createBlogForm(forms.ModelForm):
    class Meta:
        model = models.userBlog
        fields = ['Title', 'text', 'place_Img1']


class appReviewForm(forms.ModelForm):
    class Meta:
        model = models.appReview
        fields = ['comment']

ots/main/templates/main/HotelReview.html
<html>
<head>
   <link rel="stylesheet" href="/static/nicepage.css" media="screen">

    <meta name="generator" content="Nicepage 3.24.3, nicepage.com">
   <link rel="stylesheet" href="/static/fonts/material-icon/css/material-design-iconic-font.min.css">

    <link rel="stylesheet" href="/static/css/signup-style.css">
    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i">
<style>
body {
  background-image: url('/static/home/img/11.jpg');
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-size: 100% 100%;
}
</style>
</head>

  <body class="u-body" >
    <section class="u-clearfix u-palette-1-base u-section-1" id="carousel_2bcf" style="background-color: transparent;background-color: rgba(0, 0, 0, 0);">
      <div class="u-clearfix u-sheet u-valign-middle-sm u-valign-middle-xs u-sheet-1">
        <div class="u-clearfix u-expanded-width u-layout-wrap u-layout-wrap-1">
          <div class="u-layout">
            <div class="u-layout-row">
              <div class="u-container-style u-layout-cell u-size-20 u-layout-cell-1">
                <div class="u-container-layout u-container-layout-1">
                  <h6 class="u-text u-text-2 black">Call us</h6>
                  <p class="u-text u-text-3 black">1 (234) 567-891<br>1 (234) 987-654
                  </p>
                  <h6 class="u-text u-text-4 black">Location</h6>
                  <p class="u-text u-text-5 black">East West University, Dhaka<br>Bangladesh, BD
                  </p>
                </div>
              </div>
              <div class="main">

        <section class="signup">
            <!-- <img src="images/signup-bg.jpg" alt=""> -->
            <div class="container">
                <div class="signup-content">

                    <form method="POST" id="register-form" class="register-form">
					{% csrf_token %}
                        <h2 class="form-title">Write Review</h2>

						<div class="form-group">
                            <label class="u-label">Your Name</label>
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
							{{form.name}}
                        </div>
                        <div class="form-group">
                            <label class="u-label">Hotel Name</label>
                            &nbsp;&nbsp;&nbsp;&nbsp;
							{{form.hotelName}}
                        </div>
                        <div class="form-group">
							<label class="u-label align" data-align="top">Review</label>
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
							{{form.review}}
                        </div>
                        <div class="form-group">
                            <label class="u-label">Rating</label>
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
							<select name="rating" required="" id="id_rating" value="{{ form.rating }}" style="text-color:black;">
                                </select>
                        </div>

                        <button type="submit" name="signup_submit" id="submit_button" class="form-submit" value="Sign up">Submit</button>

                    </form>

                </div>
            </div>
        </section>

    </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </body>
<style>
    label{
    color:black;
    }
    select{
  width: 180px;

  color: black;
}
input{
    color:black;
}
textarea {
    color:black;
}
select option { color: black; }
.black{
    color:black;
}
</style>
</html>

ots/main/templates/main/HotelRoom.html
<html>
<head>
<style>

.rcorners2 {
  border-radius: 25px;
  border: 2px solid #73AD21;
  padding: 20px;

  height: 150px;
}

* {
  box-sizing: border-box;
}

.img-container {
  float: left;
  width: 33.33%;
  padding: 5px;
}

.clearfix::after {
  content: "";
  clear: both;
  display: table;
}
body {
  background-image: url('/static/hotel_back.jpg');
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-size: 100% 100%;
}
</style>
</head>
<body>
	{% for roomModel in roomModel %}
            {% ifequal roomModel.slug hotel_name %}
				<div class="flex justify-between">
					   <div class="mb-5">
						   <h1 class="text-3xl font-medium mb-px">
							   <a href="../hotel_page"><img src="/static/home/img/back.png" height="30px" width="30px"></a>
							   {{ mylist }}</h1>
					   </div>
				 </div>
				<div class="-mt-5 container max-w-full h-75vh flex mb-20" xmlns:rooms="http://www.w3.org/1999/xhtml"
					 xmlns:rooms="http://www.w3.org/1999/xhtml">
					<div class="h-full w-1/2 bg-center bg-cover" style="background-image:url({{room.first_photo}})"></div>
					<div class="h-full w-1/2 flex flex-wrap">
						<div class="clearfix">
				  <div class="img-container">
				  <img src="{{ roomModel.room_Img1.url }}" alt="Error" style="width:100%" height="300px" width="446">
				  </div>
				  <div class="img-container">
				  <img src="{{ roomModel.room_Img2.url }}" alt="Error" style="width:100%" height="300px" width="446">
				  </div>
				  <div class="img-container">
				  <img src="{{ roomModel.room_Img3.url }}" alt="Error" style="width:100%" height="300px" width="446">
				  </div>
				</div>

					</div>
				</div>

					<div class="w-1/2">
						<div class="flex border-section">
							<span class="mr-5 font-light">Room Type: {{ roomModel.roomtype }}e</span>
							<br>
							<span class="mr-5 font-light">Beds: {{ roomModel.beds }}</span>
							<br>
							<span class="mr-5 font-light">Baths: {{ roomModel.baths }}</span>
							<br>
							<span class="mr-5 font-light">Guests: {{ roomModel.guests }}</span>
						</div>
						<div class="border-section">
							<h5 class="font-medium text-lg mb-5">Amenities</h5>
							<p>{{ roomModel.amenities }}</p>
						</div>
						<div class="border-section">
							<h5 class="font-medium text-lg mb-5">Facility</h5>
                            <p>{{ roomModel.facilities }}</p>
						</div>
					</div>
        {% endifequal %}
{% endfor %}

 <h1 align="center">Reviews </h1>
  </div>
                        {% for hotelReview in hotelReview %}
                        {% ifequal hotelReview.hotelName hotel_name %}
						<table align="center" border="0" cellspacing="0" cellpadding="10" class="rcorners2" >
							<tr >
								<td width="200">
									{% for profile in profile %}
									{% ifequal profile.user hotelReview.user %}
									{% if profile.user_image %}
                                    <img src="{{ profile.user_image.url }}" alt="Error" height="100px" width="100px">
                                    {% endif %}
                                    {% if not profile.user_image %}
                                    <img src="/static/user.png" alt="Error" height="100px" width="100px">
                                    {% endif %}
									{% endifequal %}
									{% endfor %}
								</td>
									<td width="500" >
									<h1> {{ hotelReview.name }} </h1>
										<h4> Rating Given: {{hotelReview.rating }}/10</h4>
                                	<h4> {{ hotelReview.review }}</h4>
							</td>
								<td VALIGN=TOP width="60" style="text-align:center">
									{% ifequal user hotelReview.user %}
									&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="{% url 'articles:deleteHotelReview' hotelReview.id %}">
                                  <img src="/static/delete-circle-icon.png" height="30px" width="30px">
										{% endifequal %}
                                </a>
								</td>
                                <br>
							</tr>
						</table>
                        {% endifequal %}

                        {% endfor %}

                    </div>

					<h3 align="center"><a href="../hotelReview"><img src="/static/writeareview.png"></a></h3>

</body>
</html>

ots/main/templates/main/ResturantReview.html
<html>
<head>
   <link rel="stylesheet" href="/static/nicepage.css" media="screen">

    <meta name="generator" content="Nicepage 3.24.3, nicepage.com">
   <link rel="stylesheet" href="/static/fonts/material-icon/css/material-design-iconic-font.min.css">

    <link rel="stylesheet" href="/static/css/signup-style.css">
    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i">
<style>
body {
  background-image: url('/static/home/img/11.jpg');
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-size: 100% 100%;
}
</style>
</head>

  <body class="u-body">
    <section class="u-clearfix u-palette-1-base u-section-1" id="carousel_2bcf" style="background-color: transparent;background-color: rgba(0, 0, 0, 0);">
      <div class="u-clearfix u-sheet u-valign-middle-sm u-valign-middle-xs u-sheet-1">
        <div class="u-clearfix u-expanded-width u-layout-wrap u-layout-wrap-1">
          <div class="u-layout">
            <div class="u-layout-row">
              <div class="u-container-style u-layout-cell u-size-20 u-layout-cell-1">
                <div class="u-container-layout u-container-layout-1">
                  <h6 class="u-text u-text-2 black">Call us</h6>
                  <p class="u-text u-text-3 black">1 (234) 567-891<br>1 (234) 987-654
                  </p>
                  <h6 class="u-text u-text-4 black">Location</h6>
                  <p class="u-text u-text-5 black">East West University, Dhaka<br>Bangladesh, BD
                  </p>
                </div>
              </div>
              <div class="main">

        <section class="signup">
            <!-- <img src="images/signup-bg.jpg" alt=""> -->
            <div class="container">
                <div class="signup-content">

                    <form method="POST" id="register-form" class="register-form">
					{% csrf_token %}
                        <h2 class="form-title">Write Review</h2>

						<div class="form-group">
                            <label class="u-label">Your Name</label>
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
							{{form.name}}
                        </div>
                        <div class="form-group">
                            <label class="u-label">Hotel Name</label>
                            &nbsp;&nbsp;&nbsp;&nbsp;
							{{form.resturantName}}
                        </div>
                        <div class="form-group">
							<label class="u-label align" data-align="top">Review</label>
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
							{{form.review}}
                        </div>
                        <div class="form-group">
                            <label class="u-label">Rating</label>
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
							<select name="rating" required="" id="id_rating" value="{{ form.rating }}" style="text-color:black;">
                                </select>
                        </div>

                        <button type="submit" name="signup_submit" id="submit_button" class="form-submit" value="Sign up">Submit</button>

                    </form>

                </div>
            </div>
        </section>

    </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </body>
<style>
    label{
    color:black;
    }
    select{
  width: 180px;

  color: black;
}
input{
    color:black;
}
textarea {
    color:black;
}
select option { color: black; }
.black{
    color:black;
}
</style>
</html>

ots/main/templates/main/blogPage.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
  box-sizing: border-box;
}

/* Add a gray background color with some padding */
body {
  font-family: Arial;
  padding: 20px;
  background: #f1f1f1;
}

/* Header/Blog Title */
.header {
  padding: 30px;
  font-size: 40px;
  text-align: center;
  background: white;
}

/* Add a card effect for articles */
.card {
   background-color: white;
   padding: 20px;
   margin-top: 20px;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Responsive layout - when the screen is less than 800px wide, make the two columns stack on top of each other instead of next to each other */
@media screen and (max-width: 800px) {
.row1:after{
  content: "";
  display: table;
  clear: both;
  }
  .column{
  float: left;
  width: 50%;
  padding: 10px;
  }
* {
  box-sizing: border-box;
}
}
.row1:after{
  content: "";
  display: table;
  clear: both;
  }
  .column{
  float: left;
  width: 50%;
  padding: 10px;
  }
* {
  box-sizing: border-box;
}
</style>
</head>
<body>
{% for blogs in blogs %}
<div class="header">
  <h2>Blog Name: {{ blogs.Title }}</h2>
    {% if user == blogs.user %}
    <a href="{% url 'articles:deleteBlog' blogs.id %}">Delete</a> <a href="{% url 'articles:editBlogs' blogs.id %}">Edit</a>
    {% endif %}
</div>

<div class="row">
  <div>
    <div class="card">
      <h3>User: {{ blogs.user }}</h3>
      <h3>Post Date: {{ blogs.date }}</h3>
	  <div class="row">
         <div class="column">
                 <h3>Image</h3>
	  {% if blogs.place_Img1 %}
        <img src="{{ blogs.place_Img1.url }}" alt="Error" height="500px" width="500px">
       {% endif %}
         </div>
         <div class="column">
                 <h3>Description</h3>
             <p>{{ blogs.text }}</p>
         </div>
	   </div>

     </div>

  </div>
</div>
{% endfor %}
</body>
</html>